# Generated by Django 5.1.2 on 2024-11-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_convert_uuid_to_charfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payportal',
            name='default_currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(-3, 'Refund failed by lack of funds'), (-2, 'Refund Failed'), (-1, 'Refunded'), (0, 'Successful'), (1, 'Wait ...'), (2, 'Canceled'), (3, 'Wait for Bank'), (4, 'Canceled By User'), (5, 'Failed'), (6, 'Api Key is invalid'), (7, 'Transaction ID is invalid'), (8, 'Amount is invalid'), (9, 'Card is invalid'), (10, 'Balance is not enough')], verbose_name='Status'),
        ),
    ]
