# Generated by Django 5.1.2 on 2024-11-14 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('payment', '0002_convert_uuid_to_charfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payportal',
            name='default_currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        )
    ]
