# Generated by Django 5.1.4 on 2025-09-03 06:57

from django.db import migrations


def remove_old_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Permission.objects.filter(content_type__app_label='payment').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('payment', '0003_remove_payportal_default_currency_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_old_permissions, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='transaction',
            options={'default_permissions': ['create', 'verify', 'force_pay', 'delete_finished', 'delete_force_all'],
                     'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='payportal',
            options={'permissions': [('secret_payportal', 'Access secret data of pay portal')],
                     'verbose_name': 'Pay Portal', 'verbose_name_plural': 'Pay Portals'},
        ),
    ]
