# Generated by Django 6.0 on 2025-12-06 15:58

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_transaction_options_alter_payportal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), verbose_name='Create Date'),
        ),
    ]
